### ISSUE TITLE
Change serialization representation once again

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#20]
Avoid the problem of having to change the extension/mime type in Java for each modification of the representation we may come up with by having a field that stores some structured representation id as the only required field. 

Field name is "gbrfi" (gate bdoc representation format id) or something other uncommong which should be unique enough to also identify the json as something we know.

**Comment by greenwoodma** [comment]
Another option would be a param on the mime type. We use this in the JSON format so that you can change the path to the text field without needing multiple mime types. So for example if the text is in a field call `test` the mime type would be `text/json;text-path=test`. In your case you could have a param that specifies the representation format in use within the bdoc. Not sure which is the most sensible approach but this gives you options if you weren't keen on the magic field name.

You can see how this works here https://github.com/GateNLP/gateplugin-Format_JSON/blob/fbcf60463685c501aeab671e74e0d64b856ecabc/src/main/java/gate/corpora/GATEJSONFormat.java#L93

**Comment by johann-petrak** [comment]
Thanks, that is good to know and I think it is a good way for testing and to deal with deprecated formats or a wide range of formats which are rarely used. 

The "magic field" here is something that I hope helps with making using the format less complex for the user by avoiding having really weird long extension names or mime types to type in. 
All the names I came up with so far are maybe logical and useful to make it possible to distinguish format variations but  just terrible and awful to use.

**Comment by johann-petrak** [comment]
After some experimentation and rethinking this, it looks like the best way forward is to keep it simple and try to live without format versions for now. Nobody will ever have time to implement the code to support several legacy formats and should this really be needed at some point we can still transition to versions by detecting a "non-version" format.
